import { FolderOpen, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button, Kbd } from '@/components/ui/controls';
import { Dialog } from '@/components/ui/Dialog';
import { listProjects } from '@/lib/db';
import type { ProjectSummary } from '@/lib/project';
import { deleteProjectById, newProject, openProjectById } from '@/features/project/persistence';
import { openFilePicker } from '@/features/app/filePickers';
import { studio, useStudio } from '@/store/studio';
import { SHORTCUTS } from './useShortcuts';

export function Dialogs() {
  const dialog = useStudio((s) => s.dialog);
  const close = (open: boolean): void => {
    if (!open) studio.set({ dialog: null });
  };
  return (
    <>
      <Dialog open={dialog === 'shortcuts'} onOpenChange={close} title="Keyboard shortcuts">
        <table className="w-full text-[12px]">
          <tbody>
            {SHORTCUTS.map((s) => (
              <tr key={s.keys} className="border-b border-line last:border-0">
                <td className="py-1.5 pr-4">
                  <Kbd>{s.keys}</Kbd>
                </td>
                <td className="py-1.5 text-fg-muted">{s.action}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Dialog>
      <Dialog
        open={dialog === 'projects'}
        onOpenChange={close}
        title="Projects"
        description="Projects are stored in this browser (IndexedDB)."
        wide
      >
        {dialog === 'projects' && <ProjectList />}
      </Dialog>
      <Dialog open={dialog === 'about'} onOpenChange={close} title="About MMD Studio">
        <div className="space-y-3 text-[12px] leading-relaxed text-fg-muted">
          <p>
            A browser-only MikuMikuDance playground built with Babylon.js and{' '}
            <a
              className="text-accent hover:underline"
              href="https://github.com/noname0310/babylon-mmd"
              target="_blank"
              rel="noreferrer"
            >
              babylon-mmd
            </a>
            . Nothing is uploaded — all files stay on your device.
          </p>
          <p>
            <b className="text-fg">Legal:</b> this app ships no models, motions or music. Every MMD asset has
            its own terms of use; you are responsible for following them (credits, redistribution, commercial
            use, content restrictions) when you load, record or publish.
          </p>
          <p>The bundled “Blocky” sample is procedurally generated by this project and is public domain.</p>
        </div>
      </Dialog>
    </>
  );
}

function ProjectList() {
  const [projects, setProjects] = useState<ProjectSummary[] | null>(null);
  const current = useStudio((s) => s.project.id);
  const refresh = (): void => void listProjects().then(setProjects);
  useEffect(refresh, []);
  return (
    <div>
      <div className="mb-3 flex gap-2">
        <Button
          variant="primary"
          onClick={async () => {
            studio.set({ dialog: null });
            await newProject();
          }}
        >
          New project
        </Button>
        <Button
          onClick={() => {
            studio.set({ dialog: null });
            void openFilePicker('.zip');
          }}
        >
          Import .mmdstudio.zip…
        </Button>
      </div>
      {projects === null ? (
        <div className="py-6 text-center text-fg-muted">Loading…</div>
      ) : projects.length === 0 ? (
        <div className="py-6 text-center text-fg-muted">No saved projects yet.</div>
      ) : (
        <ul className="grid gap-2 sm:grid-cols-2">
          {projects.map((p) => (
            <li key={p.id} className="flex gap-3 rounded-md border border-line p-2">
              <div className="h-[54px] w-24 shrink-0 overflow-hidden rounded bg-bg">
                {p.thumbnail && <img src={p.thumbnail} alt="" className="h-full w-full object-cover" />}
              </div>
              <div className="min-w-0 flex-1">
                <div className="truncate font-medium">
                  {p.name} {p.id === current && <span className="text-[11px] text-accent">(open)</span>}
                </div>
                <div className="text-[11px] text-fg-dim">
                  {p.modelCount} model(s) · {new Date(p.updatedAt).toLocaleString()}
                </div>
                <div className="mt-1 flex gap-1">
                  <Button
                    size="sm"
                    disabled={p.id === current}
                    onClick={async () => {
                      studio.set({ dialog: null });
                      await openProjectById(p.id);
                    }}
                  >
                    <FolderOpen size={12} /> Open
                  </Button>
                  <Button
                    size="sm"
                    variant="danger"
                    onClick={async () => {
                      if (!confirm(`Delete “${p.name}” permanently?`)) return;
                      await deleteProjectById(p.id);
                      refresh();
                    }}
                  >
                    <Trash2 size={12} />
                  </Button>
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
